[package]
name = "neural-network"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.137", features = ["preserve_order"] }
